version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: livewire/livewire
    versions:
    - 2.3.14
    - 2.3.15
    - 2.3.16
    - 2.3.17
    - 2.3.18
    - 2.3.8
    - 2.3.9
    - 2.4.0
    - 2.4.1
    - 2.4.2
    - 2.4.3
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.9
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
